PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX agro: <http://ontology.irstea.fr/agronomictaxon/core#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX txrfrk: <http://taxref.mnhn.fr/lod/taxrank/> 
PREFIX agronto: <http://aims.fao.org/aos/agrontology#> 
PREFIX agrovoc: <http://aims.fao.org/aos/agrovoc/> 
PREFIX txrfp: <http://taxref.mnhn.fr/lod/property/> 


select ?commonName where {
?taxon txrfp:hasRank ?variable_temp0. 
?variable_temp0 rdf:type txrfrk:TaxonomicRank. 
?taxon rdfs:label ?label. 
?taxon txrfp:vernacularName ?commonName. 
filter (regex(?label, "^triticum$", "i") && lang(?commonName) ="en").
}

