PREFIX agro: <http://ontology.irstea.fr/agronomictaxon/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


select ?commonName where {
?taxon rdf:type dbo:Species.
?taxon rdfs:label ?label.
?taxon rdfs:label ?commonName.
filter (regex(?label,"^triticum$", "i") && lang(?commonName) ="fr").
}