PREFIX agro: <http://ontology.irstea.fr/agronomictaxon/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


select distinct ?specy where {
?taxon rdfs:label ?label.
?specy rdf:type dbo:Species.
?taxon rdf:type dbo:Species.
{?specy dbo:kingdom ?taxon.
}UNION
{?specy dbo:phylum ?taxon.
}UNION
{?specy dbo:classis ?taxon.
}UNION
{?specy dbo:order ?taxon.
}UNION
{?specy dbo:family ?taxon.
}UNION
{?specy dbo:genus ?taxon.
}

?specy a dbo:Species.
?specy dbo:genus ?variable_temp0.

filter (regex(?label, "^wheat$","i")).
}
